In [ ]:
!pip install kaggle

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory


In [ ]:
!kaggle datasets download -d kazanova/sentiment140

Dataset URL: https://www.kaggle.com/datasets/kazanova/sentiment140
License(s): other
sentiment140.zip: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
from zipfile import ZipFile
file_name = "sentiment140.zip"

with ZipFile(file_name, 'r') as zip:
  zip.extractall()
  print('done')

done


In [ ]:
 import numpy as np
 import pandas as pd
 import re
 from nltk.corpus import stopwords
 from nltk.stem.porter import PorterStemmer


In [ ]:
df = pd.read_csv('training.1600000.processed.noemoticon.csv',encoding='latin-1')
df.head(4)

0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY _TheSpecialOne_  \
0  0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   scotthamilton   
1  0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY        mattycus   
2  0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY         ElleCTF   
3  0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY          Karoli   

  @switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D  
0  is upset that he can't update his Facebook by ...                                                                   
1  @Kenichan I dived many times for the ball. Man...                                                                   
2    my whole body feels itchy and like its on fire                                                                    
3  @nationwideclass no, it's not behaving at all....

In [ ]:
print(df.shape)
df.tail()
df.columns
# df.dtypes

(1599999, 6)


Index(['0', '1467810369', 'Mon Apr 06 22:19:45 PDT 2009', 'NO_QUERY',
       '_TheSpecialOne_',
       '@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D'],
      dtype='object')

In [ ]:
import nltk
nltk.download('stopwords')
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
column_names =['target','id','date','flag','user','text']
df.columns = column_names
df.head()

target          id                          date      flag           user  \
0       0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY  scotthamilton   
1       0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY       mattycus   
2       0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY        ElleCTF   
3       0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY         Karoli   
4       0  1467811372  Mon Apr 06 22:20:00 PDT 2009  NO_QUERY       joy_wolf   

                                                text  
0  is upset that he can't update his Facebook by ...  
1  @Kenichan I dived many times for the ball. Man...  
2    my whole body feels itchy and like its on fire   
3  @nationwideclass no, it's not behaving at all....  
4                      @Kwesidei not the whole crew

In [ ]:
df.isnull().sum()

target    0
id        0
date      0
flag      0
user      0
text      0
dtype: int64

In [ ]:
df['target'].value_counts()

target
4    800000
0    799999
Name: count, dtype: int64

In [ ]:
df.replace({'target': {4: 1}}, inplace=True)
df['target'].value_counts()

target
1    800000
0    799999
Name: count, dtype: int64

In [ ]:
x=df['text']
y=df['target']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1279999,)
(320000,)
(1279999,)
(320000,)


In [ ]:
print(x_train[6])
print(y_train[6])

@LOLTrish hey  long time no see! Yes.. Rains a bit ,only a bit  LOL , I'm fine thanks , how's you ?
0


In [ ]:
!pip install tensorflow



In [ ]:
!pip install keras


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
tokenizer = Tokenizer(num_words=1000,lower=True)
tokenizer.fit_on_texts(x_train)



In [ ]:
X_train = tokenizer.texts_to_sequences(x_train)

X_test = tokenizer.texts_to_sequences(x_test)
print(X_train)

In [ ]:
maxlen=100
X_train = pad_sequences(X_train, padding='post', maxlen=maxlen)
#Y_train = pad_sequences(Y_train, padding='post', maxlen=maxlen)
X_test = pad_sequences(X_test, padding='post', maxlen=maxlen)
#Y_test = pad_sequences(Y_test, padding='post', maxlen=maxlen)
print(X_train)

[[ 20  66   4 ...   0   0   0]
 [138   3 674 ...   0   0   0]
 [  1  59 287 ...   0   0   0]
 ...
 [ 84   7 785 ...   0   0   0]
 [618 341 106 ...   0   0   0]
 [  1  64  80 ...   0   0   0]]


In [ ]:
from keras.utils import to_categorical
Y_train = to_categorical(y_train)
Y_test = to_categorical(y_test)
print(Y_train)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]


In [ ]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation,SimpleRNN
from keras import optimizers

X_train = np.array(X_train).reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = np.array(X_test).reshape((X_test.shape[0], X_test.shape[1], 1))
print(X_train.shape)
print(X_test.shape)

(1279999, 100, 1)
(320000, 100, 1)


In [ ]:
num_classes = 2
def rnn():
  model = Sequential()
  model.add(SimpleRNN(50,input_shape=(maxlen,1),return_sequences=False))
  model.add(Dense(num_classes))
  model.add(Activation('softmax'))
  model.summary()
  adam = optimizers.Adam(learning_rate=0.001)
  model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
  return model

In [ ]:
!pip uninstall -y scikit-learn scikeras
!pip install scikit-learn scikeras


Found existing installation: scikit-learn 1.5.1
Uninstalling scikit-learn-1.5.1:
  Successfully uninstalled scikit-learn-1.5.1
Found existing installation: scikeras 0.13.0
Uninstalling scikeras-0.13.0:
  Successfully uninstalled scikeras-0.13.0
  Using cached scikit_learn-1.5.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
  Using cached scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Using cached scikit_learn-1.5.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.4 MB)
Using cached scikeras-0.13.0-py3-none-any.whl (26 kB)


In [ ]:
from scikeras.wrappers import KerasClassifier

model = KerasClassifier(build_fn=rnn, epochs=5, batch_size=100)
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_5 (SimpleRNN)             │ (None, 50)                  │           2,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 2)                   │             102 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_5 (Activation)            │ (None, 2)                   │               0 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,702 (10.55 KB)

 Trainable params: 2,702 (10.55 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
12800/12800 ━━━━━━━━━━━━━━━━━━━━ 377s 29ms/step - accuracy: 0.5010 - loss: 0.6937
Epoch 2/5
12800/12800 ━━━━━━━━━━━━━━━━━━━━ 317s 25ms/step - accuracy: 0.5013 - loss: 0.6943
Epoch 3/5
12800/12800 ━━━━━━━━━━━━━━━━━━━━ 320s 25ms/step - accuracy: 0.5018 - loss: 0.6941
Epoch 4/5
12800/12800 ━━━━━━━━━━━━━━━━━━━━ 343s 27ms/step - accuracy: 0.5020 - loss: 0.6940
Epoch 5/5
12800/12800 ━━━━━━━━━━━━━━━━━━━━ 377s 26ms/step - accuracy: 0.5021 - loss: 0.6941


KerasClassifier(
	model=None
	build_fn=<function rnn at 0x78d901a991b0>
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=None
	metrics=None
	batch_size=100
	validation_batch_size=None
	verbose=1
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=5
	class_weight=None
)

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
y_test_= np.argmax(Y_test, axis=1)
print(accuracy_score(y_test_, y_pred))

3200/3200 ━━━━━━━━━━━━━━━━━━━━ 42s 13ms/step
0.497196875


In [ ]:
test_input = ["I love water"]
test_input = tokenizer.texts_to_sequences(test_input)
test_input=np.array(test_input)
test_input = pad_sequences(test_input, padding='post', maxlen=maxlen)
test_input = test_input.reshape((test_input.shape[0], test_input.shape[1], 1))
print(test_input.shape)
prediction = model.predict(np.array(test_input))
print(prediction)


(1, 100, 1)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[[0 1]]
